#!/usr/bin/env python3
"""
gen_data.py -- writes D4CertData.lean for the Lake project in this
directory: the certificate of multi_cap/continuation_out/certificate_d8.npz
as exact dyadic rationals, and the tables of omega, omega' and omega''
that certificate_check.py computes from the closed forms in interval
arithmetic (6001 angles here), as dyadic numbers (numerator, exponent).

Usage: python3 gen_data.py   (from this directory; needs ../../multi_cap on the path)
"""
import os, sys
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'multi_cap'))
import certificate_check as C

Z = np.load(os.path.join(HERE, '..', '..', 'multi_cap', 'continuation_out', 'certificate_d8.npz'))
d = 8

def rat(x):
    n, dnm = float(x).as_integer_ratio()
    k = dnm.bit_length() - 1
    assert dnm == 2 ** k
    return f"(({n} : Rat) / 2^{k})" if k else f"({n} : Rat)"

def dy(x):
    n, dnm = float(x).as_integer_ratio()
    k = dnm.bit_length() - 1
    assert dnm == 2 ** k
    return f"({n}, {k})"

om0, om1, om2, A_star, r_star = C.closed_forms()
us, olow, ohigh, d1lo, d1hi, du, M2 = C.omega_tables(om0, om1, om2, r_star, n=6001, n2=3000)
d1lo[0] = min(d1lo[0], 0.0)

out = ["set_option maxRecDepth 4000\n"]
out.append("/-\nD4CertData.lean: the certificate and the tables, generated by gen_data.py.\nEvery number is the exact dyadic rational denoted by a double-precision\nfloating-point number.  The tables are those of certificate_check.py:\nusRaw[i] is an upper bound of cos(gamma_i), olowRaw[i] a lower bound of\nomega(gamma_i), d1loRaw[i] and d1hiRaw[i] enclose d omega/du at cos(gamma_i),\nduRaw bounds the width of every cell in u, and m2Raw bounds |d^2 omega/du^2|\non [1/3, 1/2]; all unscaled, as values of omega itself.\n-/\n")
out.append("def f : List Rat := [" + ", ".join(rat(x) for x in Z['f']) + "]\n")
for k in range(d + 1):
    M = Z[f'F{k}']
    rows = ",\n  ".join("[" + ", ".join(rat(x) for x in row) + "]" for row in M)
    out.append(f"def F{k} : List (List Rat) := [\n  {rows}]\n")
def arr(name, vals, chunk=300):
    parts = []
    names = []
    for j in range(0, len(vals), chunk):
        sub = vals[j:j + chunk]
        body = ",\n  ".join(", ".join(dy(v) for v in sub[i:i + 6]) for i in range(0, len(sub), 6))
        names.append(f"{name}_{j // chunk}")
        parts.append(f"def {name}_{j // chunk} : Array (Int × Nat) := #[\n  {body}]\n")
    parts.append(f"def {name} : Array (Int × Nat) := " + " ++ ".join(names) + "\n")
    return "\n".join(parts)
out.append(arr("usRaw", us)); out.append(arr("olowRaw", olow)); out.append(arr("d1loRaw", d1lo)); out.append(arr("d1hiRaw", d1hi))
out.append(f"def duRaw : Int × Nat := {dy(du)}\n")
out.append(f"def m2Raw : Int × Nat := {dy(M2)}\n")
open(os.path.join(HERE, 'D4CertData.lean'), 'w').write("\n".join(out))
print("wrote D4CertData.lean:", len(us), "table entries; du =", du, "M2 =", M2)
