#!/usr/bin/env python3
"""
gen_labelled_data.py -- writes D4LabelledData.lean for the regions II_s and
II_f of the labelled certificate (thm:m23; multi_cap/labelled_certificate_check.py):

  * the tables of omega, omega', omega'' from 2 r_* down to an angle whose cosine
    exceeds a_D (18001 angles), as labelled_certificate_check.omega_tables
    computes them from the closed forms in interval arithmetic;
  * the slab constant c = 4000 r kappa (a double below its arb enclosure);
  * a_D = amax(D, D) rounded up to a double, and the double t_1 = 0.51 that
    separates II_s from II_f;
  * ds_k, the integral of A(tau) = (4 pi / 3)(3/2 - tau^2)^(3/2) over the k-th of
    256 cells of tau in [1, D/2], enclosed by doubles from arb (128 bits).

Everything else of II_s and II_f (the certificate polynomial, the shares fr,
the packing bounds amax, the Gamma envelopes and the subdivision) is computed
in Lean, by D4LabelledDomain.lean.  Every number is written as the exact
dyadic rational (numerator, exponent) that its double denotes.

Usage: python3 gen_labelled_data.py   (from this directory; needs python-flint, mpmath)
"""
import os, sys
from fractions import Fraction as Fr
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'multi_cap'))
import certificate_check as C
import labelled_certificate_check as L


def dy(x):
    n, dnm = float(x).as_integer_ratio()
    k = dnm.bit_length() - 1
    assert dnm == 2 ** k
    return f"({n}, {k})"


om0, om1, om2, A_star, r_star = C.closed_forms()
aD = L.amax(L.D, L.D)
aD_f = L.fhi(aD)
us, olow, ohigh, d1lo, d1hi, du, M2 = L.omega_tables(om0, om1, om2, r_star, aD_f)
fs = L.fr_hi(Fr(1), Fr(1, 2) + L.TAU1)
rr = Fr(1, 11) - 2 * Fr(fs)
kap = L.s_(2 + 4 * L.TAU1) / L.A(4 * L.TAU1)
c_slab = L.flo(4000 * L.A(rr) * kap)
t1 = float(Fr(1, 2) + L.TAU1)
taus = [1 + (L.H - 1) * Fr(k, L.K) for k in range(L.K + 1)]
Ss = [L.S(2 * t) for t in taus]
ds = [Ss[k] - Ss[k + 1] for k in range(L.K)]
ds_lo = [L.flo(x) for x in ds]; ds_hi = [L.fhi(x) for x in ds]
assert all(x > 0 for x in ds_lo)


def arr(name, vals, per_line=8):
    """the table as a string literal of pairs "n/k;", parsed by parsePairs in Lean
    (a string elaborates in a fraction of the time and memory of 18001 tuples)"""
    items = [dy(v)[1:-1].replace(', ', '/') + ';' for v in vals]
    lines = ["".join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
    body = "\\\n  ".join(lines)
    return f'def {name}Str : String := "\\\n  {body}"\ndef {name} : Array (Int × Nat) := parsePairs {name}Str\n'


out = []
out.append("/-\nD4LabelledData.lean: the inputs of the regions II_s and II_f of the labelled\n"
           "certificate (thm:m23), generated by gen_labelled_data.py.  usL[i] is an upper\n"
           "bound of cos(gamma_i), olowL[i] a lower bound of omega(gamma_i), d1loL[i] and d1hiL[i]\n"
           "enclose d omega/du there, duL bounds the width of every cell in u and m2L bounds\n"
           "|d^2 omega/du^2| on [1/3, a_D], all unscaled; cSlabRaw is a lower bound of the slab\n"
           "constant c = 4000 r kappa; aDRaw an upper bound of a_D = amax(D, D); t1Raw the double\n"
           "0.51; dsLoRaw[k] <= ds_k <= dsHiRaw[k], ds_k the integral of A over the k-th cell of\n"
           "tau in [1, D/2].  Each pair (n, k) is the dyadic rational n / 2^k; the long tables are\n"
           "string literals of pairs \"n/k;\" that parsePairs reads (and rejects if malformed).\n-/\n")
out.append("""/-- Read "n/k;n/k;..." (whitespace ignored) as the pairs (n, k); a malformed entry
gives (0, 0), which the checks of D4LabelledDomain then reject by order or size. -/
def parsePairs (s : String) : Array (Int × Nat) :=
  let clean := String.ofList (s.toList.filter fun c => !c.isWhitespace)
  let items := (clean.splitOn ";").filter (· ≠ "")
  items.toArray.map fun it =>
    match it.splitOn "/" with
    | [a, b] => (a.toInt?.getD 0, b.toNat?.getD 0)
    | _ => (0, 0)
""")
out.append(arr("usL", us)); out.append(arr("olowL", olow)); out.append(arr("d1loL", d1lo)); out.append(arr("d1hiL", d1hi))
out.append(f"def duL : Int × Nat := {dy(du)}\n")
out.append(f"def m2L : Int × Nat := {dy(M2)}\n")
out.append(f"def cSlabRaw : Int × Nat := {dy(c_slab)}\n")
out.append(f"def aDRaw : Int × Nat := {dy(aD_f)}\n")
out.append(f"def t1Raw : Int × Nat := {dy(t1)}\n")
out.append(arr("dsLoRaw", ds_lo)); out.append(arr("dsHiRaw", ds_hi))
open(os.path.join(HERE, 'D4LabelledData.lean'), 'w').write("\n".join(out))
print(f"wrote D4LabelledData.lean: {len(us)} angles up to u = {us[-1]:.6f}, du = {du:.3e}, M2 = {M2:.6f}; "
      f"c = {c_slab:.6f}; a_D <= {aD_f!r}; t1 = {t1!r}; {len(ds_lo)} cells")
