#!/usr/bin/env python3
"""
full_triangle_symmetry.py
==========================
Supersedes the direct, region-by-region certificate attempts elsewhere
in this directory (region_top_*.py, bandC_certificate.py,
bandBcurve_certificate.py) for the purpose of establishing Conjecture
(Direction-of-Deviation Positivity, restated) on the second arc: this
script proves that no further per-region computation on the second arc
is needed at all, because the second arc is EXACTLY the first arc in
disguise.

THE RESULT: the group generated by S=diag(1,1,1,-1) and the Hadamard
matrix H = (1/2)*[[1,1,1,1],[1,1,-1,-1],[1,-1,1,-1],[1,-1,-1,1]] (both
already used elsewhere in this project -- S in arc2_w1v2/w1v2_explore.py
to reduce the second arc's own range, H in misc/confirm_H_full_arc_symmetry.py
to reduce the first arc's) has order exactly 6, fixes u0 in every
element, and realises ALL SIX permutations of {v1, w1, v2} -- i.e. it is
(isomorphic to) the symmetric group S3 acting on these three vertices
as its full permutation group. This was not previously noticed because
S and H had only ever been used separately, each to reduce one arc's
own range to [0, pi/4]; nobody had examined the group they jointly
generate.

CONSEQUENCE: since every element of this group is an exact automorphism
of the D4 root system fixing u0 (verified below by finite exact check,
not sampling), it carries any deviated packing configuration to a
CONGRUENT one -- identical Voronoi cell volume, identical defect -- at
the image deviation direction. In particular M = S*H satisfies
M(w1) = v1 and M(v2) = w1 exactly, so it carries the second arc's own
parametrisation dev_{w1,v2}(t) = cos(t) w1 + sin(t) v2 EXACTLY onto the
first arc's parametrisation dev_{v1,w1}(t) = cos(t) v1 + sin(t) w1, for
every t (proved here symbolically for a symbolic t, not merely checked
at sample points). Hence:

    defect(theta, dev_{w1,v2}(t)) = defect(theta, dev_{v1,w1}(t))

for every theta and every t -- the second arc's defect function IS the
first arc's, not merely similar to it. Since the first arc already
carries a complete positivity certificate (all 8 regions: 7 exact
zero-margin, 1 with an explicit thin margin -- see arc1_v1w1/), the
second arc inherits that certificate automatically, at the SAME
margins, with no further computation. Combined with
third_edge_symmetry.py's earlier result (the triangle's third edge,
v1-v2, is also exactly the first arc, via S alone), ALL THREE edges of
the fundamental deviation triangle are now accounted for by this single
S3 action.

This makes the direct attempts elsewhere in this directory
(region_top_*.py -- which independently confirms part of this on the
first sub-region and stands as a genuine cross-check; bandC_certificate.py
and the box-covering middle-band certificate -- likewise independent
confirmations on the parts of the domain they covered; and
bandBcurve_certificate.py, whose symbolic derivation did not terminate)
no longer necessary for establishing the result: the background run of
bandBcurve_certificate.py was stopped once this script's result was in
hand, since continuing it could at best re-derive, by a much harder
route, a fact this script already establishes exactly.

WHAT THIS DOES NOT ESTABLISH, stated as plainly as possible: this is a
boundary-to-boundary reduction. It proves Conjecture (Direction-of-
Deviation Positivity, RESTATED -- confined to the fundamental triangle's
boundary) in full. It does NOT prove the ORIGINAL, general conjecture,
whose domain is the entire transverse 2-sphere of deviation directions:
the triangle's two-dimensional INTERIOR is a separate parameter family
that no element of this symmetry group (or any larger group we have
found) relates to the boundary, and it remains completely untouched by
any certificate or symmetry argument in this paper.
"""
import sympy as sp
import numpy as np
from scipy.spatial import HalfspaceIntersection, ConvexHull

sqrt2 = sp.sqrt(2)


def exact_group_check():
    u0 = sp.Matrix([1, 1, 0, 0]) / sqrt2
    v1 = sp.Matrix([1, -1, 0, 0]) / sqrt2
    w1 = sp.Matrix([0, 0, 1, 1]) / sqrt2
    v2 = sp.Matrix([0, 0, 1, -1]) / sqrt2

    S = sp.diag(1, 1, 1, -1)
    H = sp.Rational(1, 2) * sp.Matrix([[1, 1, 1, 1], [1, 1, -1, -1],
                                        [1, -1, 1, -1], [1, -1, -1, 1]])

    roots = []
    for i in range(4):
        for j in range(i + 1, 4):
            for si in (1, -1):
                for sj in (1, -1):
                    v = [0, 0, 0, 0]
                    v[i] = si
                    v[j] = sj
                    roots.append(sp.Matrix(v))
    roots_set = set(tuple(r) for r in roots)

    def is_root_automorphism(M):
        return set(tuple(M * r) for r in roots) == roots_set

    print("=== Basic checks (exact, Q(sqrt2)) ===")
    print("S^2 == Id:", sp.simplify(S * S - sp.eye(4)) == sp.zeros(4, 4))
    print("H^2 == Id:", sp.simplify(H * H - sp.eye(4)) == sp.zeros(4, 4))
    print("S fixes u0:", sp.simplify(S * u0 - u0) == sp.zeros(4, 1))
    print("H fixes u0:", sp.simplify(H * u0 - u0) == sp.zeros(4, 1))
    print("S is a root-system automorphism:", is_root_automorphism(S))
    print("H is a root-system automorphism:", is_root_automorphism(H))

    print()
    print("=== Generate the group <S,H> ===")
    verts = {'v1': v1, 'w1': w1, 'v2': v2}
    gens = [S, H]
    elems = [sp.eye(4)]
    changed = True
    while changed:
        changed = False
        new = []
        for a in elems:
            for g in gens:
                p = sp.simplify(a * g)
                if not any(sp.simplify(p - e) == sp.zeros(4, 4) for e in elems + new):
                    new.append(p)
                    changed = True
        elems.extend(new)
    print(f"Group order: {len(elems)}  (expect 6, i.e. S_3)")

    perms_seen = set()
    for M in elems:
        fixesu0 = sp.simplify(M * u0 - u0) == sp.zeros(4, 1)
        isauto = is_root_automorphism(M)
        img = {name: sp.simplify(M * vec) for name, vec in verts.items()}
        perm = tuple(
            next(n2 for n2, v2_ in verts.items() if sp.simplify(v - v2_) == sp.zeros(4, 1))
            for _, v in img.items()
        )
        perms_seen.add(perm)
        assert fixesu0 and isauto, "group element fails to fix u0 or is not a root automorphism!"
    print(f"Every element fixes u0 and is a root automorphism: True")
    print(f"Distinct permutations of (v1,w1,v2) realised: {len(perms_seen)}  (expect 6, all of S_3)")

    print()
    print("=== The key consequence: M = S*H maps arc2's parametrisation onto arc1's, symbolically ===")
    M = sp.simplify(S * H)
    t = sp.symbols('t', real=True)
    dev_w1v2 = sp.cos(t) * w1 + sp.sin(t) * v2
    dev_v1w1 = sp.cos(t) * v1 + sp.sin(t) * w1
    diff = sp.simplify(M * dev_w1v2 - dev_v1w1)
    print("M(dev_w1v2(t)) - dev_v1w1(t) simplified (symbolic t):", diff.T)
    print("Exactly zero for all t:", diff == sp.zeros(4, 1))
    return True


def numeric_sanity_check():
    roots = []
    for i in range(4):
        for j in range(i + 1, 4):
            for si in (1, -1):
                for sj in (1, -1):
                    v = np.zeros(4)
                    v[i] = si
                    v[j] = sj
                    roots.append(v / np.sqrt(2))
    roots = np.array(roots)

    def find(vec):
        v = np.array(vec, dtype=float)
        v /= np.linalg.norm(v)
        d = roots @ v
        idx = np.argmax(d)
        assert d[idx] > 1 - 1e-9
        return idx

    idx0 = find([1, 1, 0, 0])
    u0 = roots[idx0]
    v1 = roots[find([1, -1, 0, 0])]
    w1 = roots[find([0, 0, 1, 1])]
    v2 = roots[find([0, 0, 1, -1])]

    def n_vertices_and_defect(theta, e_perp):
        e_perp = e_perp / np.linalg.norm(e_perp)
        u1 = np.cos(theta) * u0 + np.sin(theta) * e_perp
        dirs = roots.copy()
        dirs[idx0] = u1
        Am = dirs
        bm = -np.ones(len(dirs))
        hs = np.hstack([Am, bm.reshape(-1, 1)])
        hi = HalfspaceIntersection(hs, np.zeros(4))
        hull = ConvexHull(hi.intersections, qhull_options='QJ')
        return len(hull.vertices), hull.volume - 8.0

    def dev_v1w1(t):
        return np.cos(t) * v1 + np.sin(t) * w1

    def dev_w1v2(t):
        return np.cos(t) * w1 + np.sin(t) * v2

    print()
    print("=== Numerical sanity check: breakpoint alignment across the full second-arc domain ===")
    print("(spans the C-bounded, middle, and B-bounded sub-parts of the band, and region top)")
    all_match = True
    for t_fixed in [0.02, 0.08, 0.15, 0.25, 0.40, 0.65, 0.70, 0.75, 0.78]:
        thetas = np.linspace(0.05, 1.55, 500)
        prev1 = prev2 = None
        bp1 = []
        bp2 = []
        maxdiff = 0.0
        for th in thetas:
            n1, F1 = n_vertices_and_defect(th, dev_v1w1(t_fixed))
            n2, F2 = n_vertices_and_defect(th, dev_w1v2(t_fixed))
            maxdiff = max(maxdiff, abs(F1 - F2))
            if prev1 is not None and n1 != prev1:
                bp1.append(round(th, 4))
            if prev2 is not None and n2 != prev2:
                bp2.append(round(th, 4))
            prev1, prev2 = n1, n2
        match = (bp1 == bp2)
        all_match = all_match and match
        print(f"  t={t_fixed:.2f}: breakpoints match={match}  max|defect diff| over scan={maxdiff:.2e}")
    print(f"All sampled t-values show exact breakpoint alignment: {all_match}")


if __name__ == "__main__":
    exact_group_check()
    numeric_sanity_check()
    print()
    print("CONCLUSION: the second arc requires no certificate of its own -- it is exactly")
    print("the first arc, via the S_3 symmetry group verified above. Conjecture")
    print("(Direction-of-Deviation Positivity, RESTATED) is proved in full on the")
    print("fundamental triangle's boundary. The triangle's interior is untouched by")
    print("this argument; it is covered instead by the cap inequality of sec:cap-theorem,")
    print("which gives the sign over the whole deviation sphere at once.")
