#!/usr/bin/env python3
"""
a18_other_starts.py

sec:broad-sample of the paper: greedy dense growth to 18 roots started from
roots 5 and 12 gives configurations congruent to A_18 (grown from root
0). The check is exact: it generates the group of orthogonal maps that
preserve the D4 roots from the signed coordinate permutations and the
orthogonal matrix H with rows (1,1,1,1)/2, (1,1,-1,-1)/2, (1,-1,1,-1)/2,
(1,-1,-1,1)/2 (1152 elements), and counts those that map A_18 onto
itself and onto each of the other two sets. Congruent active
sets give the same volume function up to an isometry.

Roots are indexed as in multidir_chain_hessian_extended.build_roots, and
the growth rule is that of multidir_nullspace_broad_sample.greedy_dense_m18.

Run: python a18_other_starts.py   (about a minute)
"""
import itertools
from fractions import Fraction as F

ROOTS = []
for i in range(4):
    for j in range(i + 1, 4):
        for si in (1, -1):
            for sj in (1, -1):
                v = [0] * 4
                v[i] = si
                v[j] = sj
                ROOTS.append(tuple(v))
INDEX = {r: k for k, r in enumerate(ROOTS)}
ADJ = [[sum(x * y for x, y in zip(a, b)) == 1 for b in ROOTS] for a in ROOTS]


def grow(start, m=18):
    active = [start] + [k for k in range(24) if ADJ[start][k]]
    remaining = [k for k in range(24) if k not in active]
    while len(active) < m and remaining:
        scores = sorted(((sum(ADJ[k][a] for a in active), k) for k in remaining),
                        reverse=True)
        best = scores[0][1]
        active.append(best)
        remaining.remove(best)
    return sorted(active)


def apply(M, v):
    return tuple(sum(M[i][j] * v[j] for j in range(4)) for i in range(4))


def matmul(A, B):
    return [[sum(A[i][k] * B[k][j] for k in range(4)) for j in range(4)] for i in range(4)]


def image(M, S):
    out = []
    for k in S:
        w = apply(M, ROOTS[k])
        if any(F(x).denominator != 1 for x in w):
            return None
        w = tuple(int(x) for x in w)
        if w not in INDEX:
            return None
        out.append(INDEX[w])
    return sorted(out)


def root_automorphisms():
    """The group generated by the signed coordinate permutations and H,
    as a list of distinct 4x4 rational matrices, closed under products."""
    h = F(1, 2)
    H = [[h, h, h, h], [h, h, -h, -h], [h, -h, h, -h], [h, -h, -h, h]]
    gens = [H]
    for p in itertools.permutations(range(4)):
        for s in itertools.product((1, -1), repeat=4):
            M = [[F(0)] * 4 for _ in range(4)]
            for i in range(4):
                M[i][p[i]] = F(s[i])
            gens.append(M)
    key = lambda M: tuple(tuple(r) for r in M)
    seen = {key(g): g for g in gens}
    frontier = list(seen.values())
    while frontier:
        nxt = []
        for A in frontier:
            for g in gens:
                B = matmul(A, g)
                k = key(B)
                if k not in seen:
                    seen[k] = B
                    nxt.append(B)
        frontier = nxt
    group = list(seen.values())
    assert all(image(G, range(24)) is not None for G in group)
    return group


def main():
    group = root_automorphisms()
    print("orthogonal maps preserving the D4 roots:", len(group))
    a18 = grow(0)
    print("A_18 (from root 0):", a18)
    stab = sum(1 for G in group if image(G, a18) == a18)
    print("maps sending A_18 onto itself:", stab)
    ok = True
    for start in (5, 12):
        other = grow(start)
        hits = sum(1 for G in group if image(G, a18) == other)
        print(f"from root {start}: {other}; maps sending A_18 onto it: {hits}")
        ok = ok and hits > 0
    print("both congruent to A_18:", ok)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
