/-
D4RootLattices.lean

A machine check of the finite content of the lemma "From the inner products
to the root system" (lem:root-lattice) of "The Sphere Packing Problem in Dimension 4
and the Twenty-Four-Cell Conjecture": a lattice of rank at most 4 generated by
vectors of norm 2 has at most 24 vectors of norm 2, and when it has 24 it is
the D_4 root lattice.

Everything here is finite arithmetic over the integers, settled by
`native_decide` on a bare Lean 4 toolchain, with no `sorry` and no Mathlib.

The argument that the file checks.  A lattice generated by vectors of norm 2
has a basis of such vectors, whose Gram matrix G has 2 on the diagonal and,
by Cauchy--Schwarz, an entry in {-1, 0, 1} off it.  So G ranges over a finite
set: 3^(r(r-1)/2) symmetric matrices for each rank r <= 4, of which those with
every leading principal minor positive are the positive definite ones
(Sylvester's criterion).  The vectors of norm 2 of the lattice are the integer
vectors x with x^T G x = 2.  They lie in a box that is computed exactly: with
D = det G and A_ii the (i,i) cofactor, the (i,i) entry of G^{-1} is A_ii / D,
and for any x, by Cauchy--Schwarz in the inner product G,

    x_i^2 = (e_i^T x)^2 <= (e_i^T G^{-1} e_i) (x^T G x) = 2 A_ii / D ,

so |x_i| <= floor (sqrt (floor (2 A_ii / D))).  Every integer vector in that
box is tested, and the norm-2 vectors are counted.

The file establishes:
 * for every rank r <= 4 and every such G, the count is at most 24;
 * the count 24 occurs only for r = 4 and det G = 4, and then the norm-2
   vectors contain four vectors whose Gram matrix is the Cartan matrix of D_4,
   so that the lattice contains a copy of the D_4 root lattice of the same
   determinant, hence equals it;
 * the largest counts in ranks 1, 2, 3, 4 are 2, 6, 12, 24.
-/

namespace D4RootLattices

abbrev Vec := List Int
abbrev Mat := List (List Int)

def get (M : Mat) (i j : Nat) : Int := ((M.getD i []).getD j 0)

/-- remove row i and column j -/
def minor (M : Mat) (i j : Nat) : Mat :=
  (M.eraseIdx i).map fun row => row.eraseIdx j

/-- Laplace expansion along the first row, with the order as fuel so that the
    recursion is structural -/
def detF : Nat → Mat → Int
  | 0, _ => 1
  | fuel + 1, M =>
    match M with
    | [] => 1
    | [[a]] => a
    | _ =>
      (List.range M.length).foldl (fun acc j =>
        let s : Int := if j % 2 == 0 then 1 else -1
        acc + s * get M 0 j * detF fuel (minor M 0 j)) 0

def det (M : Mat) : Int := detF M.length M

/-- the top-left k x k block -/
def leading (M : Mat) (k : Nat) : Mat :=
  (M.take k).map fun row => row.take k

def posDef (M : Mat) : Bool :=
  (List.range M.length).all fun k => det (leading M (k + 1)) > 0

/-- the quadratic form x^T M x -/
def quad (M : Mat) (x : Vec) : Int :=
  (List.range M.length).foldl (fun acc i =>
    (List.range M.length).foldl (fun acc2 j =>
      acc2 + (x.getD i 0) * get M i j * (x.getD j 0)) acc) 0

/-- the bilinear form x^T M y -/
def bil (M : Mat) (x y : Vec) : Int :=
  (List.range M.length).foldl (fun acc i =>
    (List.range M.length).foldl (fun acc2 j =>
      acc2 + (x.getD i 0) * get M i j * (y.getD j 0)) acc) 0

/-- integer square root, floor -/
def isqrt (n : Int) : Int :=
  if n <= 0 then 0 else
  let rec go (lo hi : Nat) (fuel : Nat) : Nat :=
    match fuel with
    | 0 => lo
    | fuel + 1 =>
      if lo + 1 >= hi then lo else
      let mid := (lo + hi) / 2
      if mid * mid <= n.toNat then go mid hi fuel else go lo mid fuel
  Int.ofNat (go 0 (n.toNat + 1) 64)

/-- the box bound |x_i| <= floor sqrt (floor (2 A_ii / D)) -/
def bound (M : Mat) (i : Nat) : Int :=
  let D := det M
  let A := det (minor M i i)
  isqrt ((2 * A) / D)

def range (b : Int) : List Int :=
  (List.range (2 * b.toNat + 1)).map fun k => Int.ofNat k - b

/-- all integer vectors in the box -/
def box (M : Mat) : List Vec :=
  (List.range M.length).foldl (fun acc i =>
    acc.flatMap fun v => (range (bound M i)).map fun t => v ++ [t]) [[]]

/-- the vectors of norm 2 of the lattice with Gram matrix M -/
def rootsOf (M : Mat) : List Vec :=
  (box M).filter fun x => quad M x == 2

/-- the candidate Gram matrices of rank r: 2 on the diagonal, off-diagonal
    entries in {-1, 0, 1}, symmetric -/
def pairs (r : Nat) : List (Nat × Nat) :=
  (List.range r).flatMap fun i => (List.range r).filterMap fun j =>
    if i < j then some (i, j) else none

def assignments : Nat → List (List Int)
  | 0 => [[]]
  | n + 1 => (assignments n).flatMap fun a => [-1, 0, 1].map fun t => a ++ [t]

def build (r : Nat) (a : List Int) : Mat :=
  let ps := pairs r
  (List.range r).map fun i => (List.range r).map fun j =>
    if i == j then 2 else
    let key := if i < j then (i, j) else (j, i)
    match ps.findIdx? (fun p => p == key) with
    | some k => a.getD k 0
    | none => 0

def candidates (r : Nat) : List Mat :=
  ((assignments (pairs r).length).map (build r)).filter posDef

/-- the Cartan matrix of D_4: the Gram matrix of the simple roots
    (1,-1,0,0), (0,1,-1,0), (0,0,1,-1), (0,0,1,1) -/
def cartanD4 : Mat := [[2, -1, 0, 0], [-1, 2, -1, -1], [0, -1, 2, 0], [0, -1, 0, 2]]

/-- does the root set contain four vectors with Gram matrix `cartanD4`? -/
def hasD4Basis (M : Mat) (R : List Vec) : Bool :=
  R.any fun a => bil M a a == 2 &&
    R.any fun b => bil M a b == -1 &&
      R.any fun c => bil M b c == -1 && bil M a c == 0 &&
        R.any fun d => bil M b d == -1 && bil M a d == 0 && bil M c d == 0

/-- (number of norm-2 vectors, determinant) for every candidate of rank r -/
def census (r : Nat) : List (Nat × Int) :=
  (candidates r).map fun M => ((rootsOf M).length, det M)

def maxRoots (r : Nat) : Nat :=
  (census r).foldl (fun m p => max m p.1) 0

/-- the whole check: at most 24 roots in every rank, and 24 only at rank 4,
    determinant 4, with a D_4 basis among the roots -/
def check : Bool :=
  ([1, 2, 3, 4].all fun r => (candidates r).all fun M =>
      let R := rootsOf M
      R.length <= 24 &&
      (R.length != 24 || (r == 4 && det M == 4 && hasD4Basis M R)))

theorem candidates_count : ((candidates 1).length, (candidates 2).length,
    (candidates 3).length, (candidates 4).length) = (1, 3, 23, 393) := by native_decide

theorem max_roots : (maxRoots 1, maxRoots 2, maxRoots 3, maxRoots 4) = (2, 6, 12, 24) := by native_decide

/-- the determinants at which each count occurs in rank 4: the count 24 only at
    determinant 4, the next count 20 only at determinant 5 -/
theorem rank4_top_counts :
    ((census 4).filter (fun p => p.1 == 24)).all (fun p => p.2 == 4) = true ∧
    ((census 4).filter (fun p => p.1 == 20)).all (fun p => p.2 == 5) = true ∧
    ((census 4).filter (fun p => 20 < p.1 && p.1 < 24)).length = 0 := by native_decide

theorem main : check = true := by native_decide

/-- the D_4 lattice itself is among the candidates and has 24 roots -/
theorem cartan_is_candidate : (candidates 4).contains cartanD4 = true := by native_decide
theorem cartan_roots : (rootsOf cartanD4).length = 24 := by native_decide
theorem cartan_det : det cartanD4 = 4 := by native_decide

end D4RootLattices

#print axioms D4RootLattices.main
#print axioms D4RootLattices.max_roots
#print axioms D4RootLattices.rank4_top_counts
#print axioms D4RootLattices.candidates_count
