/-
D4SecondOrder.lean: the exact content of sec:second-order of the paper, the second
order of the cell volume at the root system.

Everything is computed here from the integral root system: the 24 roots
(±1, ±1, 0, 0), the 24 vertices (±2, 0, 0, 0) and (±1, ±1, ±1, ±1) of the
scaled 24-cell, a rational basis of each tangent space, the 96 tight pairs and
their triangles, the form H of prop:hessian-d4 (by the midpoint rule over the
triangles), the 120 rows B of the first-order packing cone and c = 2 1_eta.
The only data are those of the certificate of prop:cone-min: the 43 orbits
of pairs of cone rows and the value of N on each, written by
gen_second_order_lean.py from multi_cap/second_order/exact_certificate.pkl.

The theorems say that N is nonnegative and covers every pair of rows exactly
once, that P = H + c c^T - B^T N B is symmetric and positive semidefinite (an
exact LDL^T elimination over Q in which a zero pivot is accepted only with a
zero row, 30 of them), and so that H + c c^T is copositive on the cone
{B xi >= 0}: the statement H(xi, xi) >= -(sum delta_i)^2 of prop:cone-min.
They also check the form on the push-outs (prop:hessian-d4), the equality on
the one-centre rays, and the two polynomial identities of lem:pure-push and of
the one-centre formula.  That H is the Hessian of the volume and that B are
the linearised packing constraints are the content of lem:second-variation and of the
paper, checked numerically by independent_check.py; they are not formalised.

Generated by gen_second_order_lean.py.  No Mathlib; the finite checks are
settled by native_decide, the identities by grind.
-/

set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

namespace D4SecondOrder

open Lean.Grind

/-! ## Two identities -/

section Identities
variable {α : Type} [CommRing α]

/-- lem:pure-push: `1 - (1 - η)^4 = 4η - 6η^2 + η^3 (4 - η)`. -/
theorem pure_push_expansion (x : α) : 1 - (1 - x)^4 = 4*x - 6*x^2 + x^3*(4 - x) := by
  grind

/-- The one-centre formula, times 48:
    `48 (1/3 - (1/3)(1 - δ/2)^4) = 16 - (2 - δ)^4 = 32δ - 24δ^2 + 8δ^3 - δ^4`,
    that is `vol - 8 = (2/3)δ - (1/2)δ^2 + (1/6)δ^3 - (1/48)δ^4`. -/
theorem one_centre_expansion (d : α) : 16 - (2 - d)^4 = 32*d - 24*d^2 + 8*d^3 - d^4 := by
  grind

end Identities

/-! ## The root system and the 24-cell -/

def dot (a b : List Rat) : Rat := (List.zipWith (· * ·) a b).foldl (· + ·) 0

def unit (k : Nat) (s : Rat) : List Rat := (List.range 4).map fun j => if j == k then s else 0

/-- The 24 roots (±1, ±1, 0, 0), in the order of rational_model.py. -/
def roots : List (List Rat) :=
  [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)].flatMap fun (p, q) =>
    [(1 : Rat), -1].flatMap fun sp => [(1 : Rat), -1].map fun sq =>
      (List.range 4).map fun k => if k == p then sp else if k == q then sq else 0

/-- The 24 vertices of the scaled 24-cell `{x : <x, a> <= 2}`. -/
def verts : List (List Rat) :=
  ((List.range 4).flatMap fun k => [(2 : Rat), -2].map fun s => unit k s) ++
  ([(1 : Rat), -1].flatMap fun a => [(1 : Rat), -1].flatMap fun b =>
    [(1 : Rat), -1].flatMap fun c => [(1 : Rat), -1].map fun d => [a, b, c, d])

def root (i : Nat) : List Rat := roots.getD i []
def vert (k : Nat) : List Rat := verts.getD k []

/-- A rational orthogonal basis of the tangent space at root `a`:
    `a_p e_p - a_q e_q`, then the two unit vectors off its support. -/
def basis (a : List Rat) : List (List Rat) :=
  let supp := (List.range 4).filter fun k => a.getD k 0 != 0
  let others := (List.range 4).filter fun k => a.getD k 0 == 0
  let p := supp.getD 0 0
  let q := supp.getD 1 0
  let b0 := (List.range 4).map fun k =>
    if k == p then a.getD p 0 else if k == q then -(a.getD q 0) else 0
  [b0, unit (others.getD 0 0) 1, unit (others.getD 1 0) 1]

def bas (i : Nat) (k : Nat) : List Rat := (basis (root i)).getD k []

def tight : List (Nat × Nat) :=
  (List.range 24).flatMap fun i => ((List.range 24).filter fun j => i < j && dot (root i) (root j) == 1).map fun j => (i, j)

def onFacet (i : Nat) : List Nat := (List.range 24).filter fun k => dot (vert k) (root i) == 2

def triangle (i j : Nat) : List Nat := (onFacet i).filter fun k => (onFacet j).contains k

/-! ## The form, the cone and c, in the 96 coordinates `(c_ik, eta_i)` -/

def dim : Nat := 96
def idxC (i k : Nat) : Nat := 3 * i + k
def idxEta (i : Nat) : Nat := 72 + i

abbrev Mat := Array (Array Rat)

def zeros (r c : Nat) : Mat := Array.replicate r (Array.replicate c 0)

def addAt (M : Mat) (p q : Nat) (x : Rat) : Mat :=
  M.modify p fun row => row.modify q (· + x)

/-- The sparse row of `v_i(m) = eta_i - <m', t_i>/2`, `t_i = sum_k c_ik b_ik`. -/
def rowV (i : Nat) (m : List Rat) : List (Nat × Rat) :=
  (idxEta i, 1) :: ((List.range 3).map fun k => (idxC i k, -(dot m (bas i k)) / 2))

def addOuter (M : Mat) (r s : List (Nat × Rat)) (w : Rat) : Mat :=
  r.foldl (fun M (p, x) => s.foldl (fun M (q, y) => addAt M p q (w * x * y)) M) M

def midpoint (a b : List Rat) : List Rat := List.zipWith (fun x y => (x + y) / 2) a b

/-- The form H of prop:hessian-d4: `(4/3) sum |tau_i|^2` plus, over the 96 triangles,
    `(1/3) sum over the edge midpoints of 2 v_i v_j - (v_i^2 + v_j^2)/2`. -/
def formH : Mat :=
  let M0 := (List.range 24).foldl (fun M i =>
    (List.range 3).foldl (fun M k =>
      addAt M (idxC i k) (idxC i k) ((2 : Rat) / 3 * dot (bas i k) (bas i k))) M) (zeros dim dim)
  tight.foldl (fun M (i, j) =>
    let t := (triangle i j).map vert
    let p0 := t.getD 0 []
    let p1 := t.getD 1 []
    let p2 := t.getD 2 []
    [midpoint p0 p1, midpoint p1 p2, midpoint p0 p2].foldl (fun M m =>
      let ri := rowV i m
      let rj := rowV j m
      let M := addOuter M ri rj ((1 : Rat) / 3)
      let M := addOuter M rj ri ((1 : Rat) / 3)
      let M := addOuter M ri ri ((-1 : Rat) / 6)
      addOuter M rj rj ((-1 : Rat) / 6)) M) M0

/-- The 120 rows of the cone, `B xi >= 0`: first `(eta_i + eta_j)/2 - (Lambda tau)_ij` on the
    tight pairs, `(Lambda tau)_ij = (<a_i, t_j> + <a_j, t_i>)/2`, then `eta_i`. -/
def coneRows : Mat :=
  let tightRows := tight.map fun (i, j) =>
    let r := (List.range 3).foldl (fun r k =>
      let r := r.modify (idxC j k) (· - dot (root i) (bas j k) / 2)
      r.modify (idxC i k) (· - dot (root j) (bas i k) / 2)) (Array.replicate dim (0 : Rat))
    (r.modify (idxEta i) (· + (1 : Rat) / 2)).modify (idxEta j) (· + (1 : Rat) / 2)
  let etaRows := (List.range 24).map fun i => (Array.replicate dim (0 : Rat)).set! (idxEta i) 1
  (tightRows ++ etaRows).toArray

def cvec : Array Rat := (Array.range dim).map fun p => if p ≥ 72 then 2 else 0

def get (M : Mat) (p q : Nat) : Rat := (M.getD p #[]).getD q 0

/-- `M = H + c c^T`. -/
def formM : Mat :=
  let H := formH
  (Array.range dim).map fun p => (Array.range dim).map fun q => get H p q + cvec.getD p 0 * cvec.getD q 0

/-! ## The certificate -/

--DATA--

/-- N as a symmetric 120 x 120 matrix, constant on the orbits. -/
def matN : Mat :=
  (orbits.zip nu).foldl (fun M (orb, v) =>
    orb.foldl (fun M (a, b) =>
      let M := M.modify a fun row => row.set! b v
      M.modify b fun row => row.set! a v) M) (zeros 120 120)

/-- Every unordered pair of rows lies in exactly one orbit. -/
def coversOnce : Bool :=
  let counts := orbits.foldl (fun M orb =>
    orb.foldl (fun M (a, b) => addAt M (min a b) (max a b) 1) M) (zeros 120 120)
  (List.range 120).all fun a => (List.range 120).all fun b =>
    if a ≤ b then get counts a b == 1 else true

def matMul (A B : Mat) (n m k : Nat) : Mat :=
  (Array.range n).map fun i => (Array.range k).map fun j =>
    (List.range m).foldl (fun s l => let x := get A i l; if x == 0 then s else s + x * get B l j) 0

def transpose (A : Mat) (n m : Nat) : Mat :=
  (Array.range m).map fun j => (Array.range n).map fun i => get A i j

/-- `P = H + c c^T - B^T N B`. -/
def matP : Mat :=
  let B := coneRows
  let NB := matMul matN B 120 120 dim
  let BtNB := matMul (transpose B 120 dim) NB dim 120 dim
  let M := formM
  (Array.range dim).map fun p => (Array.range dim).map fun q => get M p q - get BtNB p q

def symmetric (A : Mat) (n : Nat) : Bool :=
  (List.range n).all fun p => (List.range n).all fun q => get A p q == get A q p

/-- Exact LDL^T elimination: returns whether the matrix is positive semidefinite, and the
    number of zero pivots.  A negative pivot fails; a zero pivot is accepted only when the
    rest of its row is zero. -/
def ldlPSD (A0 : Mat) (n : Nat) : Bool × Nat := Id.run do
  let mut A := A0
  let mut zeroPivots := 0
  for k in [0:n] do
    let piv := get A k k
    if piv < 0 then
      return (false, zeroPivots)
    if piv == 0 then
      if (List.range n).any (fun j => k < j && get A k j != 0) then
        return (false, zeroPivots)
      zeroPivots := zeroPivots + 1
    else
      let rowK := A.getD k #[]
      for i in [k+1:n] do
        let aik := get A i k
        if aik != 0 then
          let m := aik / piv
          A := A.modify i fun row => (Array.range n).map fun j =>
            if j > k then row.getD j 0 - m * rowK.getD j 0 else row.getD j 0
  return (true, zeroPivots)

def quad (A : Mat) (x : Array Rat) (n : Nat) : Rat :=
  (List.range n).foldl (fun s p => (List.range n).foldl (fun s q => s + x.getD p 0 * get A p q * x.getD q 0) s) 0

def etaRay (i : Nat) : Array Rat := (Array.replicate dim (0 : Rat)).set! (idxEta i) ((1 : Rat) / 2)

def adjacent (i j : Nat) : Bool := tight.contains (i, j) || tight.contains (j, i)

/-! ## The theorems -/

theorem root_system :
    (roots.length == 24 && verts.length == 24 && tight.length == 96 &&
     (List.range 24).all (fun i => (onFacet i).length == 6) &&
     tight.all (fun (i, j) => (triangle i j).length == 3)) = true := by native_decide

theorem bases_orthogonal :
    ((List.range 24).all (fun i => (List.range 3).all (fun k =>
      dot (bas i k) (root i) == 0 && (List.range 3).all (fun l => l == k || dot (bas i k) (bas i l) == 0)))) = true := by
  native_decide

/-- prop:hessian-d4 on the push-outs: `H(eta, eta) = 2 sum_T eta_i eta_j - 4 sum eta_i^2`,
    the matrix `Adj - 4I`; and `H` is symmetric. -/
theorem form_on_pushouts :
    (symmetric formH dim &&
     (List.range 24).all (fun i => (List.range 24).all (fun j =>
       get formH (idxEta i) (idxEta j) == (if i == j then -4 else if adjacent i j then 1 else 0)))) = true := by
  native_decide

/-- The identity (eq:eta-identity) as a matrix identity: on the push-outs
    `H + c c^T = Adj + 4 (J - I)`. -/
theorem eta_identity :
    ((List.range 24).all (fun i => (List.range 24).all (fun j =>
      get formM (idxEta i) (idxEta j) == (if i == j then 0 else if adjacent i j then 5 else 4)))) = true := by
  native_decide

theorem certificate_data :
    (orbits.length == 43 && nu.length == 43 && nu.all (fun x => decide (0 ≤ x)) &&
     (nu.filter (fun x => decide (0 < x))).length == 35 && coversOnce) = true := by native_decide

/-- prop:cone-min: `P = H + c c^T - B^T N B` is symmetric and positive semidefinite,
    with 30 zero pivots, so `H + c c^T` is copositive on the cone. -/
theorem copositive_certificate : (symmetric matP dim && ldlPSD matP dim == (true, 30)) = true := by
  native_decide

/-- Equality on the one-centre rays: `H(xi, xi) + (sum delta)^2 = 0` there. -/
theorem one_centre_rays : ((List.range 24).all (fun i => quad formM (etaRay i) dim == 0)) = true := by
  native_decide

/-! ## The tilt block: the contact-cell volume under pure tilts -/

/-- The tangent field `t_i = M a_i - (<a_i, M a_i>/2) a_i` of a 4 x 4 matrix `M` (a rotation
    when `M` is antisymmetric, a strain when symmetric), in the coordinates `c_ik`. -/
def fieldVec (M : List (List Rat)) : Array Rat :=
  (Array.range dim).map fun idx =>
    if idx ≥ 72 then 0 else
    let i := idx / 3
    let k := idx % 3
    let a := root i
    let Ma := M.map fun row => dot row a
    let lam := dot a Ma / 2
    let t := List.zipWith (fun x y => x - lam * y) Ma a
    dot t (bas i k) / dot (bas i k) (bas i k)

def elemM (p q : Nat) (x y : Rat) : List (List Rat) :=
  (List.range 4).map fun r => (List.range 4).map fun s =>
    if r == p && s == q then x else if r == q && s == p then y else 0

def rotations : List (Array Rat) :=
  [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)].map fun (p, q) => fieldVec (elemM p q 1 (-1))

def strains : List (Array Rat) :=
  ([(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)].map fun (p, q) => fieldVec (elemM p q 1 1)) ++
  ([0, 1, 2].map fun p => fieldVec ((List.range 4).map fun r => (List.range 4).map fun s =>
    if r == s && r == p then (1 : Rat) else if r == s && r == p + 1 then -1 else 0))

/-- The 72 x 72 tilt block of `H` (the Hessian of the contact-cell volume in the directions
    alone) is positive semidefinite, with 15 zero pivots in an exact `LDL^T`; the six
    rotations are null for it and the nine strains are not. -/
theorem tilt_block :
    (ldlPSD formH 72 == (true, 15) &&
     rotations.all (fun v => quad formH v dim == 0) &&
     strains.all (fun v => quad formH v dim > 0)) = true := by
  native_decide

end D4SecondOrder

#print axioms D4SecondOrder.pure_push_expansion
#print axioms D4SecondOrder.one_centre_expansion
#print axioms D4SecondOrder.root_system
#print axioms D4SecondOrder.bases_orthogonal
#print axioms D4SecondOrder.form_on_pushouts
#print axioms D4SecondOrder.eta_identity
#print axioms D4SecondOrder.certificate_data
#print axioms D4SecondOrder.copositive_certificate
#print axioms D4SecondOrder.one_centre_rays
#print axioms D4SecondOrder.tilt_block
