#!/usr/bin/env python3
"""
gen_certificate_lean.py -- writes D4Certificate.lean from the three-point
certificate continuation_out/certificate_d8.npz of multi_cap/.

The floating-point numbers of the certificate are dyadic rationals; they
are written into the Lean file exactly, as integer numerators over powers
of two, so that the Lean file states the same certificate that
certificate_check.py verifies.  The Lean file then proves, by the kernel's
own evaluation (decide +kernel):

  * f_k >= 0 for k = 1, ..., 8;
  * each of the nine matrices F_0, ..., F_8 is symmetric and positive
    definite, by exact LDL^T elimination over the rationals (every pivot
    positive);
  * the bound N (N f_0 - sum f_k) / 2 - N F(1,1,1) / (6 (N - 2)) with
    N = 23 and F(1,1,1) the sum of the entries of F_0 (the matrices S_k
    vanish at (1,1,1) for k >= 1 and S_0(1,1,1) is the all-ones matrix in
    the Chebyshev basis) exceeds 92.8555703, that is, 0.0928555703 after
    the scale 1000 of the solver, which is above 8 - A_* =
    0.09285557029...

The polynomial inequality (C) on the admissible domain is verified in
interval arithmetic by certificate_check.py and is not formalised.

Usage: python3 gen_certificate_lean.py  (from this directory)
"""
import numpy as np, os

HERE = os.path.dirname(os.path.abspath(__file__))
Z = np.load(os.path.join(HERE, '..', 'multi_cap', 'continuation_out', 'certificate_d8.npz'))
d = 8

def rat(x):
    n, dnm = float(x).as_integer_ratio()
    k = dnm.bit_length() - 1
    assert dnm == 2 ** k
    return f"(({n} : Rat) / 2^{k})" if k else f"({n} : Rat)"

lines = []
lines.append("/-\nD4Certificate.lean: the exact arithmetic of the three-point certificate\nfor the pair inequality of the twenty-three contact case.\n\nThe numbers below are the certificate written by three_point_sdp.py\n(degree 8, bound fixed at 0.0929), as exact dyadic rationals.  The kernel\nchecks that f_k >= 0 for k >= 1, that every F_k is symmetric and positive\ndefinite (exact LDL^T over Q), and that the bound of the certificate\nexceeds 92.8555703 in the units of the solver, that is 0.0928555703 > 8 - A_*.\nThe polynomial inequality on the admissible domain is verified in interval\narithmetic by certificate_check.py.  Generated by gen_certificate_lean.py.\n-/\n")
lines.append("def f : List Rat := [" + ", ".join(rat(x) for x in Z['f']) + "]\n")
for k in range(d + 1):
    M = Z[f'F{k}']
    rows = ",\n  ".join("[" + ", ".join(rat(x) for x in row) + "]" for row in M)
    lines.append(f"def F{k} : List (List Rat) := [\n  {rows}]\n")
lines.append('''
/-- One step of LDL^T elimination: the pivot must be positive; the Schur
complement of the first row and column is returned. -/
def elimStep : List (List Rat) → Option (List (List Rat))
  | [] => none
  | (r :: rows) =>
    match r with
    | [] => none
    | (p :: rest) =>
      if p ≤ 0 then none else
      some (rows.map (fun row =>
        match row with
        | [] => []
        | (a :: rrest) => List.zipWith (fun x y => x - (a / p) * y) rrest rest))

/-- Every pivot of the elimination is positive: the matrix is positive definite. -/
def ldlPositive : List (List Rat) → Nat → Bool
  | _, 0 => true
  | A, n + 1 =>
    match elimStep A with
    | none => false
    | some B => ldlPositive B n

def entry (M : List (List Rat)) (i j : Nat) : Rat :=
  ((M.getD i []).getD j 0)

def symmetric (M : List (List Rat)) : Bool :=
  (List.range M.length).all fun i =>
    (List.range M.length).all fun j => entry M i j == entry M j i

def square (M : List (List Rat)) : Bool := M.all fun r => r.length == M.length

def posDef (M : List (List Rat)) : Bool :=
  square M && symmetric M && ldlPositive M M.length

def sumAll (M : List (List Rat)) : Rat := (M.map (fun r => r.foldl (· + ·) 0)).foldl (· + ·) 0

def N : Rat := 23
def f0 : Rat := f.getD 0 0
def sumF : Rat := f.foldl (· + ·) 0
/-- N (N f_0 - f(1)) / 2 - N F(1,1,1) / (6 (N - 2)), with F(1,1,1) the sum of the entries of F_0. -/
def bound : Rat := N * (N * f0 - sumF) / 2 - N * sumAll F0 / (6 * (N - 2))

theorem f_nonneg : (f.drop 1).all (fun x => decide (0 ≤ x)) = true := by decide +kernel
''')
for k in range(d + 1):
    lines.append(f"theorem F{k}_posdef : posDef F{k} = true := by decide +kernel\n")
lines.append('''
/-- 92.8555703 / 1000 = 0.0928555703 exceeds 8 - A_* = 0.09285557029... -/
theorem bound_exceeds : bound > (928555703 : Rat) / 10000000 := by decide +kernel

#print axioms f_nonneg
''')
for k in range(d + 1):
    lines.append(f"#print axioms F{k}_posdef\n")
lines.append("#print axioms bound_exceeds\n")
open(os.path.join(HERE, 'D4Certificate.lean'), 'w').write("".join(lines))
print("wrote D4Certificate.lean")
