#!/usr/bin/env python3
"""
gen_data.py -- writes KissData.lean and Kiss26Data.lean for the Lake project in
this directory: the three-point certificates of thm:kissing-stable and
thm:twenty-six (multi_cap/cardinality_certificates)
as exact dyadic rationals, with the threshold t, the least double at or above t
(the top of the domains of the branch and bound) and the tolerances e1, e2 (the
largest doubles at or below the decimals of the paper), exactly as
multi_cap/certify_cardinality.py reads them: every f_k is taken as the rational
its double denotes (a negative one would be replaced by 0; none is), and every
F_k is symmetrised exactly.

Usage: python3 gen_data.py   (from this directory)
"""
import os
from fractions import Fraction as Fr
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
CERTS = os.path.join(HERE, '..', '..', 'multi_cap', 'cardinality_certificates')

# name, file, e1, e2, the decimal forms of e1 and e2 in the paper
RUNS = [('cert8', 'cert_d8_t0.50650.npz', '1e-6', '1e-5'),
        ('cert10', 'cert_d10_t0.50800.npz', '1e-6', '7e-5')]
# the certificate of thm:twenty-six, written to its own module so that the
# checks of KissMain8 and KissMain10 need not be rebuilt
RUNS26 = [('cert26', 'cert_d10_t0.51468.npz', '1e-6', '2.9e-4')]


def rat(q):
    q = Fr(q)
    k = q.denominator.bit_length() - 1
    assert q.denominator == 2 ** k, q
    return f"(({q.numerator} : Rat) / 2^{k})" if k else f"({q.numerator} : Rat)"


def pair(q):
    """a dyadic rational as (numerator, exponent), read back by dy"""
    q = Fr(q)
    k = q.denominator.bit_length() - 1
    assert q.denominator == 2 ** k, q
    return f"({q.numerator}, {k})"


def dec(txt):
    q = Fr(txt)
    return f"(({q.numerator} : Rat) / {q.denominator})" if q.denominator != 1 else f"({q.numerator} : Rat)"


def below(txt):
    x = float(txt)
    return x if Fr(x) <= Fr(txt) else float(np.nextafter(x, -np.inf))


def top(t):
    x = float(t)
    return x if Fr(x) >= t else float(np.nextafter(x, np.inf))


out = ["set_option maxRecDepth 4000\n\n/-\nKissData.lean: the certificates of thm:kissing-stable, generated by gen_data.py.\n"
       "Every entry (n, k) is the exact dyadic rational n / 2^k denoted by a\ndouble-precision "
       "floating-point number; tDec, e1Dec, e2Dec are the decimals of the paper,\n"
       "and top, e1, e2 the doubles the branch and bound uses (checked against\n"
       "them in KissDomain).\n-/\n"
       "structure Cert where\n  d : Nat\n  f : List Rat                 -- f_1, ..., f_d\n"
       "  F : List (List (List Rat))   -- F_0, ..., F_d, F_k of size d - k + 1\n"
       "  tDec : Rat\n  top : Rat\n  e1 : Rat\n  e2 : Rat\n  e1Dec : Rat\n  e2Dec : Rat\n\n"
       "/-- (n, k) denotes n / 2^k. -/\ndef dy (x : Int × Nat) : Rat := (x.1 : Rat) / (2 ^ x.2 : Nat)\n"]
def emit(name, fn, e1, e2):
    Z = np.load(os.path.join(CERTS, fn))
    d = len(Z['f'])
    t = Fr(repr(float(Z['t'])))
    f = [max(Fr(float(x)), Fr(0)) for x in Z['f']]
    Fs = []
    for k in range(d + 1):
        M = [[Fr(float(x)) for x in row] for row in Z[f'F{k}']]
        n = len(M)
        for i in range(n):
            for j in range(i + 1, n):
                m = (M[i][j] + M[j][i]) / 2; M[i][j] = M[j][i] = m
        Fs.append(M)
    body = [f"def {name}_f : List (Int × Nat) := [" + ", ".join(pair(x) for x in f) + "]", ""]
    for k, M in enumerate(Fs):
        rows = ",\n  ".join("[" + ", ".join(pair(x) for x in row) + "]" for row in M)
        body += [f"def {name}_F{k} : List (List (Int × Nat)) := [\n  {rows}]", ""]
    body += [f"def {name} : Cert where",
             f"  d := {d}",
             f"  f := {name}_f.map dy",
             "  F := [" + ", ".join(f"{name}_F{k}" for k in range(d + 1)) + "].map (·.map (·.map dy))",
             f"  tDec := {dec(repr(float(Z['t'])))}",
             f"  top := {rat(Fr(top(t)))}",
             f"  e1 := {rat(Fr(below(e1)))}",
             f"  e2 := {rat(Fr(below(e2)))}",
             f"  e1Dec := {dec(e1)}",
             f"  e2Dec := {dec(e2)}", ""]
    return "\n".join(body)


for run in RUNS:
    out.append(emit(*run))
open(os.path.join(HERE, 'KissData.lean'), 'w').write("\n".join(out))
print("wrote KissData.lean:", ", ".join(r[0] for r in RUNS))
out26 = ["/-\nKiss26Data.lean: the certificate of thm:twenty-six, generated by gen_data.py,\n"
         "in the format of KissData.lean.\n-/\nimport KissData\n\nset_option maxRecDepth 4000\n"]
for run in RUNS26:
    out26.append(emit(*run))
open(os.path.join(HERE, 'Kiss26Data.lean'), 'w').write("\n".join(out26))
print("wrote Kiss26Data.lean:", ", ".join(r[0] for r in RUNS26))
